version: '3.7'

services:

### APP Container ##########################################

    app:
      build:
        context: .
        args:
          - APP_MNT_PATH=${APP_MNT_PATH}
      image: softruck_challenge_node
      volumes:
        - ${APP_PATH}:${APP_MNT_PATH}
      ports:
        - "3000:3000"
      networks:
        - frontend
        - backend

### Mysql Container ##################################

    svc-mysql:
      image: mysql
      command:
        - "--default-authentication-plugin=mysql_native_password"
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "3306:3306"
      networks:
        - backend
        
networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"